### ISSUE TITLE
missing config/pwa.php

### ISSUE THREAD

**Issue by abrhambas01** [OwenMelbz/laravel-pwa-manifest#1]
Where is this 
I'm using Laravel 5.4. Followed your instruction but didn't see this : 

config/pwa_manifest.php 

Where is this ?? 
I'm using Laravel 5.4. Followed your instruction but didn't see this : 

pwa_manifest.php  in the folder inside the config folder from the app folder

**Comment by OwenMelbz** [comment]
@abrhambas01 did you do `php artisan vendor:publish` - which is Step 3 - this publishes the config

**Comment by abrhambas01** [comment]
@OwenMelbz yes i did

**Comment by OwenMelbz** [comment]
I've just tested it locally, and its definitely publishing for me.

All it does it copy the file, you can go to https://github.com/OwenMelbz/laravel-pwa-manifest/blob/master/src/config/config.php and just save the file into your configs folder as `pwa_manifest.php`

**Comment by marcellus-jeanbernard** [comment]
Hello 
I am new to PWA could help me how can i integrate pwa in my laravel app ?

my name is Jean Bernard MARCELLUS

**Comment by OwenMelbz** [comment]
@marcellus-jeanbernard StackOverflow would be better for specific questions on how to do things, Github Issues is to report bugs.

There isn't a single answer to how to do it.

PWA is made up of lots of different concepts which you pick and choose.

All this package does is help you generate a manifest file from a Laravel application
